# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

annotations:
  artifacthub.io/category: streaming-messaging
  artifacthub.io/license: MIT
  artifacthub.io/maintainers: |
    - name: FMJdev
      email: info@fmj.dev
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: ntfy
      image: docker.io/binwiederhier/ntfy:v2.11.0
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: ntfy GitHub Repository
      url: https://github.com/binwiederhier/ntfy
    - name: ntfy Documentation
      url: https://docs.ntfy.sh/
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
apiVersion: v2
appVersion: 2.11.0
kubeVersion: ">=1.26"
name: ntfy
version: 0.0.1
description: ntfy lets you send push notifications to your phone or desktop via scripts from any computer, using simple HTTP PUT or POST requests
home: https://github.com/binwiederhier/ntfy
icon: https://raw.githubusercontent.com/binwiederhier/ntfy/main/web/public/static/images/ntfy.png
keywords:
  - pubsub
  - messaging
  - notification
  - desktop
  - mobile
  - ntfy
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: FMJdev
    email: info@fmj.dev
