apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{- include "vaultwarden.labels" . | nindent 4 }}
  {{- with .Values.configMapAnnotations -}}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
# DATA_FOLDER=data
# DATABASE_URL=data/db.sqlite3
# DATABASE_URL=mysql://user:password@host[:port]/database_name
# DATABASE_URL=postgresql://user:password@host[:port]/database_name

# DATABASE_MAX_CONNS=10

# DATABASE_TIMEOUT=30
# DATABASE_CONN_INIT=""


# RSA_KEY_FILENAME=data/rsa_key
# ICON_CACHE_FOLDER=data/icon_cache
# ATTACHMENTS_FOLDER=data/attachments
# SENDS_FOLDER=data/sends
# TMP_FOLDER=data/tmp


# TEMPLATES_FOLDER=/path/to/templates

# RELOAD_TEMPLATES=false

# IP_HEADER=X-Real-IP

# ICON_CACHE_TTL=2592000
# ICON_CACHE_NEGTTL=259200


# WEB_VAULT_FOLDER=web-vault/
# WEB_VAULT_ENABLED=true

# WEBSOCKET_ENABLED=false

# WEBSOCKET_ADDRESS=0.0.0.0
# WEBSOCKET_PORT=3012

# PUSH_ENABLED=true
# PUSH_INSTALLATION_ID=CHANGEME
# PUSH_INSTALLATION_KEY=CHANGEME
# PUSH_RELAY_URI=https://push.bitwarden.com

# SENDS_ALLOWED=true

# EMERGENCY_ACCESS_ALLOWED=true

# ORG_EVENTS_ENABLED=false

# EMAIL_CHANGE_ALLOWED=true

# EVENTS_DAYS_RETAIN=


# ORG_GROUPS_ENABLED=false

# JOB_POLL_INTERVAL_MS=30000
# SEND_PURGE_SCHEDULE="0 5 * * * *"
# TRASH_PURGE_SCHEDULE="0 5 0 * * *"
# INCOMPLETE_2FA_SCHEDULE="30 * * * * *"
# EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE="0 3 * * * *"
# EMERGENCY_REQUEST_TIMEOUT_SCHEDULE="0 7 * * * *"
# EVENT_CLEANUP_SCHEDULE="0 10 0 * * *"
# EXTENDED_LOGGING=true
# LOG_TIMESTAMP_FORMAT="%Y-%m-%d %H:%M:%S.%3f"

# LOG_FILE=/path/to/log
# USE_SYSLOG=false
# LOG_LEVEL=Info
# ENABLE_DB_WAL=true

# DB_CONNECTION_RETRIES=15

# ICON_SERVICE=internal

# ICON_REDIRECT_CODE=302

# DISABLE_ICON_DOWNLOAD=false
# ICON_DOWNLOAD_TIMEOUT=10
# ICON_BLACKLIST_REGEX='^(192\.168\.0\.[0-9]+|192\.168\.1\.[0-9]+)$'
# ICON_BLACKLIST_NON_GLOBAL_IPS=true

# DISABLE_2FA_REMEMBER=false
# EMAIL_ATTEMPTS_LIMIT=3
# EMAIL_EXPIRATION_TIME=600
# EMAIL_TOKEN_SIZE=6

# SIGNUPS_ALLOWED=true

# SIGNUPS_VERIFY=false

# SIGNUPS_VERIFY_RESEND_TIME=3600

# SIGNUPS_VERIFY_RESEND_LIMIT=6

# SIGNUPS_DOMAINS_WHITELIST=example.com,example.net,example.org

# ORG_CREATION_USERS=
# ORG_CREATION_USERS=none
# ORG_CREATION_USERS=admin1@example.com,admin2@example.com

# ADMIN_TOKEN=Vy2VyYTTsKPv8W5aEOWUbB/Bt3DEKePbHmI4m9VcemUMS2rEviDowNAFqYi1xjmp
# DISABLE_ADMIN_TOKEN=false
# INVITATIONS_ALLOWED=true
# INVITATION_ORG_NAME=Vaultwarden

# INVITATION_EXPIRATION_HOURS=120

# ORG_ATTACHMENT_LIMIT=
# USER_ATTACHMENT_LIMIT=

# TRASH_AUTO_DELETE_DAYS=

# INCOMPLETE_2FA_TIME_LIMIT=3

# PASSWORD_ITERATIONS=350000
# PASSWORD_HINTS_ALLOWED=true
# SHOW_PASSWORD_HINT=false

# DOMAIN=https://vw.domain.tld:8443
# ALLOWED_IFRAME_ANCESTORS=

# LOGIN_RATELIMIT_SECONDS=60
# LOGIN_RATELIMIT_MAX_BURST=10

# ADMIN_RATELIMIT_SECONDS=300
# ADMIN_RATELIMIT_MAX_BURST=3
# ADMIN_SESSION_LIFETIME=20

# YUBICO_CLIENT_ID=11111
# YUBICO_SECRET_KEY=AAAAAAAAAAAAAAAAAAAAAAAA
# YUBICO_SERVER=http://yourdomain.com/wsapi/2.0/verify

# DUO_IKEY=<Integration Key>
# DUO_SKEY=<Secret Key>
# DUO_HOST=<API Hostname>


# AUTHENTICATOR_DISABLE_TIME_DRIFT=false
# ROCKET_ADDRESS=0.0.0.0
# ROCKET_PORT=80  # Defaults to 80 in the Docker images, or 8000 otherwise.
# ROCKET_WORKERS=10
# ROCKET_TLS={certs="/path/to/certs.pem",key="/path/to/key.pem"}


# SMTP_HOST=smtp.domain.tld
# SMTP_FROM=vaultwarden@domain.tld
# SMTP_FROM_NAME=Vaultwarden
# SMTP_SECURITY=starttls # ("starttls", "force_tls", "off") Enable a secure connection. Default is "starttls" (Explicit - ports 587 or 25), "force_tls" (Implicit - port 465) or "off", no encryption (port 25)
# SMTP_PORT=587          # Ports 587 (submission) and 25 (smtp) are standard without encryption and with encryption via STARTTLS (Explicit TLS). Port 465 (submissions) is used for encrypted submission (Implicit TLS).
# SMTP_USERNAME=username
# SMTP_PASSWORD=password
# SMTP_TIMEOUT=15

# USE_SENDMAIL=false
# SENDMAIL_COMMAND="/path/to/sendmail"

# SMTP_AUTH_MECHANISM="Plain"


# HELO_NAME=
# SMTP_EMBED_IMAGES=false
# SMTP_DEBUG=false
# SMTP_ACCEPT_INVALID_HOSTNAMES=false
# SMTP_ACCEPT_INVALID_CERTS=false
# REQUIRE_DEVICE_EMAIL=false

# HIBP_API_KEY=
