apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{- include "vaultwarden.labels" . | nindent 4 }}
  {{- with .Values.configMapAnnotations -}}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  DOMAIN: {{ .Values.vaultwarden.domain }}
  WEB_VAULT_ENABLED: {{ .Values.vaultwarden.web.enabled }}
  SENDS_ALLOWED: {{ .Values.vaultwarden.allowSends }}
  EMERGENCY_ACCESS_ALLOWED: {{ .Values.vaultwarden.allowEmergencyAccess }}
  ORG_EVENTS_ENABLED: {{ .Values.vaultwarden.enableOrgEvents }}
  EMAIL_CHANGE_ALLOWED: {{ .Values.vaultwarden.allowEmailChange }}
  DISABLE_ADMIN_TOKEN: {{ .Values.vaultwarden.adminToken.disable }}
  DATA_FOLDER: {{ .Values.vaultwarden.paths.data }}
  {{- if .Values.vaultwarden.retainEventsDays -}}
  EVENTS_DAYS_RETAIN: {{ .Values.vaultwarden.retainEventsDays }}
  {{- end -}}
  IP_HEADER: {{ .Values.vaultwarden.ipHeader }}
  DISABLE_2FA_REMEMBER: {{ .Values.vaultwarden.disable2FARemember }}
  {{- if .Values.vaultwarden.orgCreationUsers -}}
  ORG_CREATION_USERS: {{ .Values.vaultwarden.orgCreationUsers | quote }}
  {{- end -}}
  {{- if .Values.vaultwarden.allowedIframeAncestors }}
  ALLOWED_IFRAME_ANCESTORS: {{ .Values.vaultwarden.allowedIframeAncestors }}
  {{- end -}}
  EMAIL_ATTEMPTS_LIMIT: {{ .Values.vaultwarden.email.attemptsLimit }}
  EMAIL_EXPIRATION_TIME: {{ .Values.vaultwarden.email.tokenExpirationTime }}
  EMAIL_TOKEN_SIZE: {{ .Values.vaultwarden.email.tokenSize }}
  {{- if and .Values.vaultwarden.email.smtp.host .Values.vaultwarden.email.smtp.from -}}
  SMTP_HOST: {{ .Values.vaultwarden.email.smtp.host }}
  SMTP_FROM: {{ .Values.vaultwarden.email.smtp.from }}
  SMTP_FROM_NAME: {{ .Values.vaultwarden.email.smtp.fromName | default "Vaultwarden" }}
  SMTP_SECURITY: {{ .Values.vaultwarden.email.smtp.security }}
  SMTP_PORT: {{ .Values.vaultwarden.email.smtp.port }}
  SMTP_USERNAME: {{ .Values.vaultwarden.email.smtp.username }}
  SMTP_PASSWORD: {{ .Values.vaultwarden.email.smtp.password }}
  SMTP_TIMEOUT: {{ .Values.vaultwarden.email.smtp.timeout }}
  SMTP_AUTH_MECHANISM: {{ .Values.vaultwarden.email.smtp.auth }}
  SMTP_EMBED_IMAGES: {{ .Values.vaultwarden.email.smtp.embedImages }}
  SMTP_DEBUG: {{ .Values.vaultwarden.email.smtp.debug }}
  SMTP_ACCEPT_INVALID_HOSTNAMES: {{ .Values.vaultwarden.email.smtp.acceptInvalidHostnames }}
  SMTP_ACCEPT_INVALID_CERTS: {{ .Values.vaultwarden.email.smtp.acceptInvalidCertificates }}
  REQUIRE_DEVICE_EMAIL: {{ .Values.vaultwarden.email.smtp.requireDeviceEmail }}
  HELO_NAME: {{ .Values.vaultwarden.email.smtp.heloName }}
  {{- end -}}
  {{- if .Values.vaultwarden.websocket.enabled -}}
  WEBSOCKET_ENABLED: {{ .Values.vaultwarden.websocket.enabled }}
  WEBSOCKET_ADDRESS: {{ .Values.vaultwarden.websocket.address }}
  WEBSOCKET_PORT: {{ .Values.vaultwarden.websocket.port }}
  {{- end -}}
  


##################### SECRETS

# ADMIN_TOKEN=Vy2VyYTTsKPv8W5aEOWUbB/Bt3DEKePbHmI4m9VcemUMS2rEviDowNAFqYi1xjmp

#####################



# DATABASE_URL=data/db.sqlite3
# DATABASE_URL=mysql://user:password@host[:port]/database_name
# DATABASE_URL=postgresql://user:password@host[:port]/database_name

# DATABASE_MAX_CONNS=10

# DATABASE_TIMEOUT=30
# DATABASE_CONN_INIT=""





# TEMPLATES_FOLDER=/path/to/templates

# RELOAD_TEMPLATES=false


# ICON_CACHE_TTL=2592000
# ICON_CACHE_NEGTTL=259200





# PUSH_ENABLED=true
# PUSH_INSTALLATION_ID=CHANGEME
# PUSH_INSTALLATION_KEY=CHANGEME
# PUSH_RELAY_URI=https://push.bitwarden.com






# ORG_GROUPS_ENABLED=false

# JOB_POLL_INTERVAL_MS=30000
# SEND_PURGE_SCHEDULE="0 5 * * * *"
# TRASH_PURGE_SCHEDULE="0 5 0 * * *"
# INCOMPLETE_2FA_SCHEDULE="30 * * * * *"
# EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE="0 3 * * * *"
# EMERGENCY_REQUEST_TIMEOUT_SCHEDULE="0 7 * * * *"
# EVENT_CLEANUP_SCHEDULE="0 10 0 * * *"
# EXTENDED_LOGGING=true
# LOG_TIMESTAMP_FORMAT="%Y-%m-%d %H:%M:%S.%3f"

# LOG_FILE=/path/to/log
# USE_SYSLOG=false
# LOG_LEVEL=Info
# ENABLE_DB_WAL=true

# DB_CONNECTION_RETRIES=15

# ICON_SERVICE=internal

# ICON_REDIRECT_CODE=302

# DISABLE_ICON_DOWNLOAD=false
# ICON_DOWNLOAD_TIMEOUT=10
# ICON_BLACKLIST_REGEX='^(192\.168\.0\.[0-9]+|192\.168\.1\.[0-9]+)$'
# ICON_BLACKLIST_NON_GLOBAL_IPS=true




# SIGNUPS_ALLOWED=true

# SIGNUPS_VERIFY=false

# SIGNUPS_VERIFY_RESEND_TIME=3600

# SIGNUPS_VERIFY_RESEND_LIMIT=6

# SIGNUPS_DOMAINS_WHITELIST=example.com,example.net,example.org




# INVITATIONS_ALLOWED=true
# INVITATION_ORG_NAME=Vaultwarden

# INVITATION_EXPIRATION_HOURS=120

# ORG_ATTACHMENT_LIMIT=
# USER_ATTACHMENT_LIMIT=

# TRASH_AUTO_DELETE_DAYS=

# INCOMPLETE_2FA_TIME_LIMIT=3

# PASSWORD_ITERATIONS=350000
# PASSWORD_HINTS_ALLOWED=true
# SHOW_PASSWORD_HINT=false


# LOGIN_RATELIMIT_SECONDS=60
# LOGIN_RATELIMIT_MAX_BURST=10

# ADMIN_RATELIMIT_SECONDS=300
# ADMIN_RATELIMIT_MAX_BURST=3
# ADMIN_SESSION_LIFETIME=20

# YUBICO_CLIENT_ID=11111
# YUBICO_SECRET_KEY=AAAAAAAAAAAAAAAAAAAAAAAA
# YUBICO_SERVER=http://yourdomain.com/wsapi/2.0/verify

# DUO_IKEY=<Integration Key>
# DUO_SKEY=<Secret Key>
# DUO_HOST=<API Hostname>


# AUTHENTICATOR_DISABLE_TIME_DRIFT=false
# ROCKET_ADDRESS=0.0.0.0
# ROCKET_PORT=80  # Defaults to 80 in the Docker images, or 8000 otherwise.
# ROCKET_WORKERS=10
# ROCKET_TLS={certs="/path/to/certs.pem",key="/path/to/key.pem"}




# USE_SENDMAIL=false
# SENDMAIL_COMMAND="/path/to/sendmail"



# HIBP_API_KEY=
