apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{- include "vaultwarden.labels" . | nindent 4 }}
  {{- with .Values.configMapAnnotations -}}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{-/* General configuration */-}}
  DOMAIN: {{ .Values.vaultwarden.domain }}
  WEB_VAULT_ENABLED: {{ .Values.vaultwarden.web.enabled }}
  SENDS_ALLOWED: {{ .Values.vaultwarden.allowSends }}
  EMERGENCY_ACCESS_ALLOWED: {{ .Values.vaultwarden.allowEmergencyAccess }}
  ORG_EVENTS_ENABLED: {{ .Values.vaultwarden.enableOrgEvents }}
  ORG_GROUPS_ENABLED: {{ .Values.vaultwarden.enableOrgGroups }}
  EMAIL_CHANGE_ALLOWED: {{ .Values.vaultwarden.allowEmailChange }}
  DISABLE_ADMIN_TOKEN: {{ .Values.vaultwarden.adminToken.disable }}
  DATA_FOLDER: {{ .Values.vaultwarden.paths.data }}
  {{- if .Values.vaultwarden.retainEventsDays -}}
  EVENTS_DAYS_RETAIN: {{ .Values.vaultwarden.retainEventsDays }}
  {{- end -}}
  IP_HEADER: {{ .Values.vaultwarden.ipHeader }}
  DISABLE_2FA_REMEMBER: {{ .Values.vaultwarden.disable2FARemember }}
  {{- if .Values.vaultwarden.orgCreationUsers -}}
  ORG_CREATION_USERS: {{ .Values.vaultwarden.orgCreationUsers | quote }}
  {{- end -}}
  {{- if .Values.vaultwarden.allowedIframeAncestors }}
  ALLOWED_IFRAME_ANCESTORS: {{ .Values.vaultwarden.allowedIframeAncestors }}
  {{- end -}}
  {{-/* Database configuration */-}}
  {{- if not .Values.vaultwarden.database.existingSecret.name -}}
  DATABASE_URL: {{ include "vaultwarden.db.uri" . }}
  {{- end -}}
  DATABASE_MAX_CONNS: {{ .Values.vaultwarden.database.maxConnections }}
  DATABASE_TIMEOUT: {{ .Values.vaultwarden.database.timeout }}
  DB_CONNECTION_RETRIES: {{ .Values.vaultwarden.database.connectionRetries }}
  {{- if (eq .Values.vaultwarden.database.type "sqlite") -}}
  DATABASE_CONN_INIT: {{ include "vaultwarden.db.conn_init" . }}
  {{- end -}}
  {{- if .Values.vaultwarden.database.enableWAL -}}
  ENABLE_DB_WAL: {{ .Values.vaultwarden.database.enableWAL }}
  {{- end -}}
  {{-/* Email/SMTP configuration */-}}
  EMAIL_ATTEMPTS_LIMIT: {{ .Values.vaultwarden.email.attemptsLimit }}
  EMAIL_EXPIRATION_TIME: {{ .Values.vaultwarden.email.tokenExpirationTime }}
  EMAIL_TOKEN_SIZE: {{ .Values.vaultwarden.email.tokenSize }}
  {{- if and .Values.vaultwarden.email.smtp.host .Values.vaultwarden.email.smtp.from -}}
  SMTP_HOST: {{ .Values.vaultwarden.email.smtp.host }}
  SMTP_FROM: {{ .Values.vaultwarden.email.smtp.from }}
  SMTP_FROM_NAME: {{ .Values.vaultwarden.email.smtp.fromName | default "Vaultwarden" }}
  SMTP_SECURITY: {{ .Values.vaultwarden.email.smtp.security }}
  SMTP_PORT: {{ .Values.vaultwarden.email.smtp.port }}
  {{- end -}}
  {{- if not .Values.vaultwarden.email.smtp.existingSecret.name -}}
  SMTP_USERNAME: {{ .Values.vaultwarden.email.smtp.username }}
  SMTP_PASSWORD: {{ .Values.vaultwarden.email.smtp.password }}
  {{- end -}}
  SMTP_TIMEOUT: {{ .Values.vaultwarden.email.smtp.timeout }}
  SMTP_AUTH_MECHANISM: {{ .Values.vaultwarden.email.smtp.auth }}
  SMTP_EMBED_IMAGES: {{ .Values.vaultwarden.email.smtp.embedImages }}
  SMTP_DEBUG: {{ .Values.vaultwarden.email.smtp.debug }}
  SMTP_ACCEPT_INVALID_HOSTNAMES: {{ .Values.vaultwarden.email.smtp.acceptInvalidHostnames }}
  SMTP_ACCEPT_INVALID_CERTS: {{ .Values.vaultwarden.email.smtp.acceptInvalidCertificates }}
  REQUIRE_DEVICE_EMAIL: {{ .Values.vaultwarden.email.smtp.requireDeviceEmail }}
  HELO_NAME: {{ .Values.vaultwarden.email.smtp.heloName }}
  {{- if .Values.vaultwarden.email.smtp.sendmail.enabled -}}
  {{- with .Values.vaultwarden.email.smtp.sendmail -}}
  USE_SENDMAIL: {{ .enabled }}
  {{- if .path -}}
  SENDMAIL_COMMAND: {{ .path }}
  {{- end -}}
  {{- end -}}
  {{-/* Websocket configuration */-}}
  {{- if .Values.vaultwarden.websocket.enabled -}}
  WEBSOCKET_ENABLED: {{ .Values.vaultwarden.websocket.enabled }}
  WEBSOCKET_ADDRESS: {{ .Values.vaultwarden.websocket.address }}
  WEBSOCKET_PORT: {{ .Values.vaultwarden.websocket.port }}
  {{- end -}}
  {{-/* Rate limits configuration */-}}
  LOGIN_RATELIMIT_SECONDS: {{ .Values.vaultwarden.limits.logins.ratelimitSeconds }}
  LOGIN_RATELIMIT_MAX_BURST: {{ .Values.vaultwarden.limits.logins.ratelimitMaxBurst }}
  ADMIN_RATELIMIT_SECONDS: {{ .Values.vaultwarden.limits.logins.adminRatelimitSeconds }}
  ADMIN_RATELIMIT_MAX_BURST: {{ .Values.vaultwarden.limits.logins.adminRatelimitMaxBurst }}
  ADMIN_SESSION_LIFETIME: {{ .Values.vaultwarden.limits.logins.adminSessionLifetime }}
  {{- if .Values.vaultwarden.limits.attachments.orgLimit -}}
  ORG_ATTACHMENT_LIMIT: {{ .Values.vaultwarden.limits.attachments.orgLimit }}
  {{- end -}}
  {{- if .Values.vaultwarden.limits.attachments.userLimit -}}
  USER_ATTACHMENT_LIMIT: {{ .Values.vaultwarden.limits.attachments.userLimit }}
  {{- end -}}
  {{-/* Password configuration */-}}
  PASSWORD_ITERATIONS: {{ .Values.vaultwarden.passwords.iterations }}
  PASSWORD_HINTS_ALLOWED: {{ .Values.vaultwarden.passwords.hintsAllowed }}
  SHOW_PASSWORD_HINT: {{ .Values.vaultwarden.passwords.showHint }}
  {{-/* Signup configuration */-}}
  SIGNUPS_ALLOWED: {{ .Values.vaultwarden.signup.allowed }}
  SIGNUPS_VERIFY: {{ .Values.vaultwarden.signup.verify }}
  SIGNUPS_VERIFY_RESEND_TIME: {{ .Values.vaultwarden.signup.verifyResendTime }}
  SIGNUPS_VERIFY_RESEND_LIMIT: {{ .Values.vaultwarden.signup.verifyResendLimit }}
  {{- if .Values.vaultwarden.signup.domainWhitelist -}}
  SIGNUPS_DOMAINS_WHITELIST: {{ .Values.vaultwarden.signup.domainWhitelist }}
  {{- end -}}
  {{-/* Authentication configuration */-}}
  AUTHENTICATOR_DISABLE_TIME_DRIFT: {{ .Values.vaultwarden.auth.authenticatorDisableTimeDrift }}
  INCOMPLETE_2FA_TIME_LIMIT: {{ .Values.vaultwarden.auth.incomplete2FATimeLimit }}
  {{- if .Values.vaultwarden.auth.yubikey.enable -}}
  YUBICO_CLIENT_ID: {{ .Values.vaultwarden.auth.yubikey.clientId }}
  YUBICO_SECRET_KEY: {{ .Values.vaultwarden.auth.yubikey.clientSecret }}
  YUBICO_SERVER: {{ .Values.vaultwarden.auth.yubikey.server }}
  {{- end -}}
  {{- if .Values.vaultwarden.auth.duo.enable -}}
  DUO_IKEY: {{ .Values.vaultwarden.auth.duo.integrationKey }}
  DUO_SKEY: {{ .Values.vaultwarden.auth.duo.secretKey }}
  DUO_HOST: {{ .Values.vaultwarden.auth.duo.host }}
  {{- end -}}
  {{-/* Invitation configuration */-}}
  INVITATIONS_ALLOWED: {{ .Values.vaultwarden.invitations.allowed }}
  INVITATION_ORG_NAME: {{ .Values.vaultwarden.invitations.orgName }}
  INVITATION_EXPIRATION_HOURS: {{ .Values.vaultwarden.invitations.expirationHours }}
  {{-/* Push notification configuration */-}}
  {{- if .Values.vaultwarden.pushNotifications.enabled -}}
  PUSH_ENABLED: {{ .Values.vaultwarden.pushNotifications.enabled }}
  PUSH_INSTALLATION_ID: {{ .Values.vaultwarden.pushNotifications.installationId }}
  PUSH_INSTALLATION_KEY: {{ .Values.vaultwarden.pushNotifications.installationKey }}
  {{- if .Values.vaultwarden.pushNotifications.relayUri -}}
  PUSH_RELAY_URI: {{ .Values.vaultwarden.pushNotifications.relayUri }}
  {{- end -}}
  {{- end -}}
  {{-/* HIBP integration configuration */-}}
  {{- if (and .Values.vaultwarden.hibpApiKey.value (not .Values.vaultwarden.hibpApiKey.existingSecret.name))-}}
  HIBP_API_KEY: {{ .Values.vaultwarden.hibpApiKey.value }}
  {{- end -}}
  {{-/* Job scheduler configuration */-}}
  JOB_POLL_INTERVAL_MS: {{ .Values.vaultwarden.jobScheduler.pollIntervalMS }}
  SEND_PURGE_SCHEDULE: {{ .Values.vaultwarden.jobScheduler.sendPurgeSchedule | quote }}
  TRASH_PURGE_SCHEDULE: {{ .Values.vaultwarden.jobScheduler.trashPurgeSchedule | quote }}
  INCOMPLETE_2FA_SCHEDULE: {{ .Values.vaultwarden.jobScheduler.incomplete2FASchedule | quote }}
  EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE: {{ .Values.vaultwarden.jobScheduler.emergencyNotificationReminder | quote }}
  EMERGENCY_REQUEST_TIMEOUT_SCHEDULE: {{ .Values.vaultwarden.jobScheduler.emergencyRequestTimeout | quote }}
  EVENT_CLEANUP_SCHEDULE: {{ .Values.vaultwarden.jobScheduler.eventCleanup | quote }}
  {{- if .Values.vaultwarden.jobScheduler.trashAutoDeleteDays -}}
  TRASH_AUTO_DELETE_DAYS: {{ .Values.vaultwarden.jobScheduler.trashAutoDeleteDays }}
  {{- end -}}
  {{-/* Logging configuration */-}}
  LOG_LEVEL: {{ .Values.vaultwarden.logs.level }}
  EXTENDED_LOGGING: {{ .Values.vaultwarden.logs.extended }}
  LOG_TIMESTAMP_FORMAT: {{ .Values.vaultwarden.logs.timestampFormat }}
  USE_SYSLOG: {{ .Values.vaultwarden.logs.useSyslog }}
  {{- if .Values.vaultwarden.logs.file -}}
  LOG_FILE: {{ .Values.vaultwarden.logs.file }}
  {{- end -}}
  {{-/* Templates configuration */-}}
  {{- if .Values.vaultwarden.templates.folder -}}
  TEMPLATES_FOLDER: {{ .Values.vaultwarden.templates.folder }}
  RELOAD_TEMPLATES: {{ .Values.vaultwarden.templates.reload }}
  {{- end -}}
  {{-/* Icons configuration */-}}
  {{- if not .Values.vaultwarden.icons.disableDownloading -}}
  DISABLE_ICON_DOWNLOAD: {{ .Values.vaultwarden.icons.disableDownloading }}
  ICON_SERVICE: {{ .Values.vaultwarden.icons.service }}
  ICON_REDIRECT_CODE: {{ .Values.vaultwarden.icons.redirectCode }}
  ICON_DOWNLOAD_TIMEOUT: {{ .Values.vaultwarden.icons.downloadTimeout }}
  ICON_BLACKLIST_REGEX: {{ .Values.vaultwarden.icons.blacklistRegex | squote }}
  ICON_BLACKLIST_NON_GLOBAL_IPS: {{ .Values.vaultwarden.icons.blacklistNonGlobalIPs }}
  ICON_CACHE_TTL: {{ .Values.vaultwarden.icons.cache.ttl }}
  ICON_CACHE_NEGTTL: {{ .Values.vaultwarden.icons.cache.negttl }}
  {{- end -}}
  {{/* Rust's 'rocket' configuration */}}
  ROCKET_ADDRESS: {{ .Values.vaultwarden.rocket.address }}
  ROCKET_PORT: {{ .Values.vaultwarden.rocket.port }}
  ROCKET_WORKERS: {{ .Values.vaultwarden.rocket.workers }}
  ROCKET_TLS: {{ .Values.vaultwarden.rocket.tls }}

##################### SECRETS

  # ADMIN_TOKEN=Vy2VyYTTsKPv8W5aEOWUbB/Bt3DEKePbHmI4m9VcemUMS2rEviDowNAFqYi1xjmp
  # SMTP_USERNAME: {{ .Values.vaultwarden.email.smtp.username }}
  # SMTP_PASSWORD: {{ .Values.vaultwarden.email.smtp.password }}
  # DATABASE_URL: {{ include "vaultwarden.db.uri" . }}
  # HIBP_API_KEY: {{ .Values.vaultwarden.hibpApiKey.value }}

#####################













