{{- if eq (include "vaultwarden.resourceType" .) "Deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  {{- include "vaultwarden.podSpec" . | nindent 2}}
{{- end -}}