{{- if (not .Values.vaultwarden.adminToken.existingSecret.name) -}}
{{- /*
Admin UI secret
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.secrets.admin" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{ include "vaultwarden.labels" $ | nindent 4 }}
    {{- toYaml .Values.secret.labels | nindent 4 -}}
  {{- if .Values.secret.annotations }}
  annotations:
      {{ toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  ADMIN_TOKEN: {{ .Values.vaultwarden.adminToken.value | b64enc | quote }}
{{- end }}
---
{{- if (not .Values.vaultwarden.email.smtp.existingSecret.name ) -}}
{{- /*
SMTP secret
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.secrets.smtp" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{ include "vaultwarden.labels" $ | nindent 4 }}
    {{- toYaml .Values.secret.labels | nindent 4 -}}
  {{- if .Values.secret.annotations }}
  annotations:
      {{ toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: "kubernetes.io/basic-auth"
data:
  username: {{ .Values.vaultwarden.email.smtp.username | b64enc | quote }}
  password: {{ .Values.vaultwarden.email.smtp.password | b64enc | quote }}
{{- end }}
---
{{- if (not .Values.vaultwarden.database.existingSecret.name) -}}
{{- /*
Database secret
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.secrets.db" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{ include "vaultwarden.labels" $ | nindent 4 }}
    {{- toYaml .Values.secret.labels | nindent 4 -}}
  {{- if .Values.secret.annotations }}
  annotations:
      {{ toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  uri: {{ include "vaultwarden.db.uri" . | b64enc | quote }}
{{- end }}
---
{{- if (not .Values.vaultwarden.hibpApiKey.existingSecret.name) -}}
{{- /*
HaveIBeenPwned secret
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.secrets.hibp" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{ include "vaultwarden.labels" $ | nindent 4 }}
    {{- toYaml .Values.secret.labels | nindent 4 -}}
  {{- if .Values.secret.annotations }}
  annotations:
      {{ toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  apiKey: {{ .Values.vaultwarden.hibpApiKey.value | b64enc | quote }}
{{- end }}
