{{- if not (.Values.vaultwarden.adminToken.existingSecret) -}}
{{-/* 
Admin UI secret
*/-}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.secrets.admin" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{ include "vaultwarden.labels" $ | nindent 4 }}
type: Opaque
data:
  ADMIN_TOKEN: {{ .Values.vaultwarden.adminToken.value | b64enc | quote }}
{{- end -}}
---
{{- if not (.Values.vaultwarden.smtp.existingSecret) -}}
{{-/* 
SMTP secret
*/-}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.secrets.smtp" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{ include "vaultwarden.labels" $ | nindent 4 }}
type: "kubernetes.io/basic-auth"
data:
  username: {{ .Values.vaultwarden.smtp.username | b64enc | quote }}
  password: {{ .Values.vaultwarden.smtp.password | b64enc | quote }}
{{- end -}}
---
{{- if not (.Values.vaultwarden.database.existingSecret) -}}
{{-/* 
Database secret
*/-}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.secrets.db" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{ include "vaultwarden.labels" $ | nindent 4 }}
type: Opaque
data:
  uri: {{ include "vaultwarden.db.uri" . | b64enc | quote }}
{{- end -}}
---
{{- if not (.Values.vaultwarden.hibpApiKey.existingSecret ) -}}
{{-/* 
HaveIBeenPwned secret
*/-}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.secrets.hibp" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
    {{ include "vaultwarden.labels" $ | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.vaultwarden.hibpApiKey.value | b64enc | quote }}
{{- end -}}