{{- if eq (include "vaultwarden.resourceType" .) "StatefulSet" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "vaultwarden.fullname" . }}
  {{- include "vaultwarden.podSpec" . | nindent 2 }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.vaultwarden.data.pvc.reclaimPolicy }}
    whenScaled: {{ .Values.vaultwarden.data.pvc.reclaimPolicy }}
{{- end }}
