apiVersion: v1
kind: Service
metadata:
  name: {{ include "linkstack.fullname" . }}
  labels:
    {{- include "linkstack.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels -}}
    {{- end }}
  {{- if .Values.service.annotations -}}
  annotations:
  {{- toYaml .Values.service.annotations }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.https }}
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "linkstack.selectorLabels" . | nindent 4 }}
