{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubenav.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubenav.labels" . | nindent 4 }}
    app.kubernetes.io/component: kubenav
rules:
  {{- if .Values.rbac.rules }}
  {{ toYaml .Values.rbac.rules | nindent 2 }}
  {{- end }}
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubenav.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubenav.labels" . | nindent 4 }}
    app.kubernetes.io/component: kubenav
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubenav.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubenav.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
