# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

apiVersion: v2
appVersion: 2.11.2
kubeVersion: ">=1.26"
name: gobackup
version: 0.1.0
description: GoBackup is a CLI and Web UI for database backups to local, cloud or remote storage with notification support
home: https://gobackup.github.io/
icon: https://user-images.githubusercontent.com/5518/205909959-12b92929-4ac5-4bb5-9111-6f9a3ed76cf6.png
keywords:
  - cli
  - web-ui
  - backup
  - database
  - cloud-storage
  - s3
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: FMJ Studios Helm Authors
    email: info@fmj.studio
  - name: FMJdev
    email: info@fmj.dev
annotations:
  artifacthub.io/category: storage
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: 654213659810F05D16A7EDECB6C4D653E669D643
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/654213659810F05D16A7EDECB6C4D653E669D643
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: gobackup
      image: docker.io/huacnlee/gobackup:v2.11.2
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Support
      url: https://github.com/fmjstudios/helm/issues
    - name: GoBackup Documentation
      url: https://gobackup.github.io/
    - name: GoBackup GitHub Repository
      url: https://github.com/gobackup/gobackup
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
  # ref: https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/changes: |
    - kind: added
      description: RBAC manifests
    - kind: added
      description: Networking manifests (Ingress, Service)
    - kind: added
      description: full Deployment
    - kind: added
      description: Configuration manifests (ConfigMap, Secret)
    - kind: added
      description: PDB
    - kind: added
      description: values.yaml schema file
    - kind: changed
      description: updated README with values table