{{- /*
  TLS passphrase secret
*/}}
{{- if not .Values.uptimeKuma.certs.passphrase.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptimeKuma.secrets.tls-passphrase" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.secretLabels }}
      {{ toYaml .Values.secretLabels | nindent 4 -}}
    {{- end }}
    app.kubernetes.io/component: linkwarden
    {{- include "uptimeKuma.labels" . | nindent 4 }}
    {{- if .Values.secretAnnotations }}
  annotations:
      {{ toYaml .Values.secretAnnotations | nindent 4 -}}
    {{- end }}
type: Opaque
data:
  passphrase: {{ .Values.uptimeKuma.certs.passphrase.value | b64enc | quote }}
{{- end }}
---
{{- /*
  Cloudflare Tunnel token secret
*/}}
{{- if not .Values.uptimeKuma.cloudflaredToken.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptimeKuma.secrets.cloudflared-token" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.secretLabels }}
      {{ toYaml .Values.secretLabels | nindent 4 -}}
    {{- end }}
    app.kubernetes.io/component: linkwarden
    {{- include "uptimeKuma.labels" . | nindent 4 }}
    {{- if .Values.secretAnnotations }}
  annotations:
      {{ toYaml .Values.secretAnnotations | nindent 4 -}}
    {{- end }}
type: Opaque
data:
  token: {{ .Values.uptimeKuma.cloudflaredToken.value | b64enc | quote }}
{{- end }}
---