{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "popeye.fullname" . }}
  labels:
    {{- include "popeye.labels" . | nindent 4 }}
    app.kubernetes.io/component: popeye
rules:
  {{- if .Values.rbac.rules }}
  {{ toYaml .Values.rbac.rules | nindent 2 }}
  {{- end }}
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - namespaces
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
      - pods
      - secrets
      - serviceaccounts
      - services
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - statefulsets
      - replicasets
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["get", "list"]
  - apiGroups: ["batch.k8s.io"]
    resources:
      - cronjobs
      - jobs
    verbs: ["get", "list"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gateway-classes
      - gateways
      - httproutes
    verbs: ["get", "list"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
      - podsecuritypolicies
    verbs: ["get", "list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "popeye.fullname" . }}
  labels:
    {{- include "popeye.labels" . | nindent 4 }}
    app.kubernetes.io/component: popeye
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "popeye.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "popeye.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
