environments:
  default:
    values: []
---
releases:
  - chart: ingress-nginx/ingress-nginx
    name: ingress-nginx
    namespace: ingress-nginx
    version: 4.9.0
    installed: true
    values:
      - controller:
          updateStrategy:
            type: RollingUpdate
            rollingUpdate:
              maxUnavailable: 1
          hostPort:
            enabled: true
          terminationGracePeriodSeconds: 0
          service:
            type: NodePort
          watchIngressWithoutClass: true
          nodeSelector:
            ingress-ready: "true"
          tolerations:
            - key: "node-role.kubernetes.io/master"
              operator: "Equal"
              effect: "NoSchedule"
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Equal"
              effect: "NoSchedule"
          config:
            enable-real-ip: "true"
            # forwarded-for-header: "X-Real-IP"
            allow-snippet-annotations: true
          publishService:
            enabled: false
          extraArgs:
            publish-status-address: "localhost"

  - chart: jetstack/cert-manager
    name: cert-manager
    namespace: cert-manager
    version: v1.13.3
    installed: true
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args: ["apply", "-k", "kustomize"]
    values:
      - installCRDs: true
        ingressShim:
          defaultIssuerKind: ClusterIssuer
