apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linkwarden.configmaps.general" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: linkwarden
  {{- include "linkwarden.labels" . | nindent 4 }}
  {{- if .Values.configMapLabels }}
    {{- toYaml .Values.configMapLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.configMapAnnotations }}
  annotations:
    {{- toYaml .Values.configMapAnnotations | nindent 4 }}
  {{- end }}
data:
  {{/* General configuration */}}
  NEXTAUTH_URL: {{ .Values.linkwarden.domain }}
  {{- if and .Values.linkwarden.nextAuthSecret.value (not .Values.linkwarden.nextAuthSecret.existingSecret.name) }}
  NEXTAUTH_SECRET: {{ .Values.linkwarden.nextAuthSecret.value }}
  {{- end }}
  {{- if not .Values.linkwarden.database.existingSecret.name }}
  DATABASE_URL: {{ include "linkwarden.db.uri" . }}
  {{- end }}
  PAGINATION_TAKE_COUNT: {{ .Values.linkwarden.paginationTakeCount }}
  STORAGE_FOLDER: {{ .Values.linkwarden.data.filesystem.rootPath }}
  AUTOSCROLL_TIMEOUT: {{ .Values.linkwarden.autoscrollTimeout }}
  RE_ARCHIVE_LIMIT: {{ .Values.linkwarden.rearchiveLimit }}
  {{- if .Values.linkwarden.maxFileSize }}
  NEXT_PUBLIC_MAX_FILE_SIZE: {{ .Values.linkwarden.maxFileSize }}
  {{- end }}
  {{- if .Values.linkwarden.maxLinksPerUser }}
  MAX_LINKS_PER_USER: {{ .Values.linkwarden.maxLinksPerUser }}
  {{- end }}
  {{- if .Values.linkwarden.archiveTakeCount }}
  ARCHIVE_TAKE_COUNT: {{ .Values.linkwarden.archiveTakeCount }}
  {{- end }}
  {{- if .Values.linkwarden.browserTimeout }}
  BROWSER_TIMEOUT: {{ .Values.linkwarden.browserTimeout }}
  {{- end }}
  {{- if .Values.linkwarden.ignoreUnauthorizedCA }}
  IGNORE_UNAUTHORIZED_CA: {{ .Values.linkwarden.ignoreUnauthorizedCA }}
  {{- end }}
---
{{- range $_, $v := .Values.linkwarden.auth.sso }}
{{- $providerArg := (dict "provider" $v.provider) }}
{{- $provider := $v.provider }}
{{- $issuer := $v.issuer }}
{{- $issuerList := list (include "linkwarden.auth.providers.withIssuers" $) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "linkwarden.configmaps.auth" $) $v.provider }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: linkwarden
  {{- include "linkwarden.labels" $ | nindent 4 }}
  {{- if $.Values.configMapLabels }}
    {{- toYaml $.Values.configMapLabels | nindent 4 }}
  {{- end }}
  {{- if $.Values.configMapAnnotations }}
  annotations:
    {{- toYaml $.Values.configMapAnnotations | nindent 4 }}
  {{- end }}
data:
  {{ include "linkwarden.auth.envs.nextPublicEnable" $providerArg }}: "true"
  {{- if $v.customName }}
  {{ include "linkwarden.auth.envs.customName" $providerArg }}: {{ $v.customName }}
  {{- end }}
  {{- if has $issuer $issuerList }}
  {{- if $v.issuer -}}
  {{ include "linkwarden.auth.envs.issuer" $providerArg }}: {{ $issuer }}
  {{- end }}
  {{- end }}
  {{- if (eq $provider "atlassian") }}
  {{- if $v.scope }}
  {{ printf "%s_SCOPE" $provider | upper }}: {{ $v.scope }}
  {{- end }}
  {{- end }}
  {{- if (eq $provider "foursquare") }}
  {{- if $v.apiVersion }}
  {{ printf "%s_APIVERSION" $provider | upper }}: {{ $v.apiVersion }}
  {{- end }}
  {{- end }}
  TEST: {{ $issuerList | squote }}
---
{{- end }}