ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: mkcert-development-issuer
  hosts:
    - host: uptime-kuma.helm.private
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: uptime-kuma-ingress-tls
      hosts:
        - uptime-kuma.helm.private

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

startupProbe:
  enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 1
