# Default Helm values for fmjstudios/linkwarden.
# Reference: https://github.com/fmjstudios/helm

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section Linkwarden Image parameters
##

## Linkwarden Server Image
## ref: https://hub.docker.com/r/linkwarden/server/tags
## @param image.registry [string, default: docker.io] The Docker registry to pull the image from
## @param image.repository [string, default: linkwarden/server] The registry repository to pull the image from
## @param image.tag [string, default: '1.30.1-alpine'] The image tag to pull
## @param image.digest [string] The image digest to pull
## @param image.pullPolicy [string, default: IfNotPresent] The Kubernetes image pull policy
## @param image.pullSecrets [array] A list of secrets to use for pulling images from private registries

image:
  registry: ghcr.io
  repository: linkwarden/linkwarden
  tag: "v2.4.8"
  digest: ""
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []

## @section Linkwarden name overrides
##

## @param nameOverride String to partially override linkwarden.fullname
##
nameOverride: ""

## @param fullnameOverride String to fully override linkwarden.fullname
##
fullnameOverride: ""

## @section Linkwarden Configuration parameters
##

## Linkwarden configuration
## ref: https://github.com/dani-garcia/linkwarden/wiki/Configuration-overview
## @param linkwarden.domain [string] The domain name to give to Linkwarden

linkwarden:
  ## The domain of the Linkwarden installation, to be re-used as the NextAuth URL
  ##
  domain: ""

  ## Used to encrypt the NextAuth.js JWT, and to hash email verification tokens.
  ##
  nextAuthSecret:
    ## The value for the NextAuth secret
    ##
    value: ""

    ## Fetch the NextAuth secret from an existing Secret
    ##
    existingSecret:
      ## The name of the existing Secret from which to fetch the secret
      ##
      name: ""

      ## The name of the key within the Secret which contains the NextAuth Secret
      ##
      key: ""

  ## The number of links to fetch every time you reach the bottom of the webpage
  ##
  paginationTakeCount: 20

  ## The amount of time to wait for the website to be archived (in seconds).
  ##
  autoscrollTimeout: 30

  ## Adjusts how often a user can trigger a new archive for each link (in minutes).
  ##
  rearchiveLimit: 5

  ## Optionally set a maximum file size
  ##
  maxFileSize: ""

  ## Optionally set the maximum amount of links a single user can create
  ##
  maxLinksPerUser: ""

  ## Optionally set the number of archives to fetch
  ##
  archiveTakeCount: ""

  ## Optionally set timeout duration for the browser
  ##
  browserTimeout: ""

  ## Optionally ignore unauthorized Certificate Authorities
  ## (Allow inscure TLS connections)
  ##
  ignoreUnauthorizedCA: false

  ## Paths to use inside tha applications container for file storage.
  ##
  data:
    ## The storage type to use for data, can be either 'filesystem' or 's3'
    ##
    storageType: filesystem

    ## Filesystem data settings
    ##
    filesystem:
      ## The root path for data be stored in.
      ##
      rootPath: /data

      ## Kubernetes PVC settings
      ##
      pvc:
        ## The size given to the PVC for the above data paths
        ##
        size: 5Gi

        ## The storageClass given to PVCs created from the above data
        ##
        storageClass: standard

        ## The resourcePolicy given to PVCs created from the above data
        ##
        reclaimPolicy: Retain

    ## S3 data settings
    ##
    s3:
      ## The name of the S3 bucket to be used for the Linkwarden files
      ##
      bucketName: linkwarden

      ## The S3 endpoint to use for uploading and modifying data within before
      ## mentioned bucket
      ##
      endpoint: s3.eu-central-1.amazonaws.com

      ## The AWS region the S3 bucket is located in
      ##
      region: eu-central-1

      ## Use path-style bucket addresses instead of AWS' DNS subdomain style
      ##
      forcePathStyle: false

      ## The S3 Access Key for before mentioned bucket
      ##
      accessKey:
        ## The value for the S3 Access Key, to be used within a Kubernetes secret
        ##
        value: ""

        ## Use an existing Secret for the S3 Access Key
        ##
        existingSecret:
          ## The name of the existing secret
          ##
          name: ""
          ## The key name within the existing Secret containing the S3 Access Key
          ##
          key: ""

      ## The S3 Secret Key for before mentioned bucket
      ##
      secretKey:
        ## The value for the S3 Secret Key, to be used within a Kubernetes secret
        ##
        value: ""

        ## Use an existing Secret for the S3 Secret Key
        ##
        existingSecret:
          ## The name of the existing secret
          ##
          name: ""
          ## The key name within the existing Secret containing the S3 Secret Key
          ##
          key: ""

  ## Database settings
  ##
  database:
    ## Provide the username to the Linkwarden PostgreSQL database. Providing an 'existingSecret' overrides the value
    ## since the secret has to contain the entire database URI
    ##
    user: ""

    ## Provide the password to the Linkwarden PostgreSQL database. Providing an 'existingSecret' overrides the value
    ## since the secret has to contain the entire database URI
    ##
    password: ""

    ## Provide the host to the Linkwarden PostgreSQL database. Providing an 'existingSecret' overrides the value
    ## since the secret has to contain the entire database URI
    ##
    host: ""

    ## Provide the port to the Linkwarden PostgreSQL database. Providing an 'existingSecret' overrides the value
    ## since the secret has to contain the entire database URI
    ##
    port: ""

    ## Provide the name to the Linkwarden PostgreSQL database. Providing an 'existingSecret' overrides the value
    ## since the secret has to contain the entire database URI
    ##
    name: ""

    ## Manually provide the entire URI to the Linkwarden PostgreSQL database. Providing an 'existingSecret' overrides
    ## the value
    ##
    uri: ""

    ## Provide an existing secret containing the entire Database URI at the specified key
    ##
    existingSecret:
      name: ""
      key: ""

  ## Authentication settings
  ##
  auth:
    ## Disable registration for Linkwarden
    ##
    disableRegistration: false

    ## Enable credential logins for Linkwarden
    ##
    enableCredentials: true

    ## Disable new SSO users
    ##
    disableNewSSOUsers: false

    ## SSO Providers
    ## Officially supported and tested are only Authentik and Keycloak other SSO
    ## providers are solely provided for completeness
    ## ref: https://docs.linkwarden.app/self-hosting/sso-oauth
    ##
    sso:
      - provider: "authentik"
        customName: "authentik-custom"
        issuer: "authentik"
        clientId: "test"
        clientSecret: "test"
        existingSecret: ""

  ## SMTP settings
  ##
  smtp:
    ## Enable E-mail integration within Linkwarden
    ##
    enabled: false

    ## The email address from which Linkwarden will send mails
    ## e.g.: "vaultwarden@domain.tld"
    ##
    fromAddress: ""

    ## The mail server from which Linkwarden will send mails
    ## e.g.: "mx.domain.tld"
    ##
    server: ""

## @section Linkwarden ConfigMap parameters
##

## @param configMapAnnotations Define extra annotations for the Linkwarden ConfigMap
##
configMapAnnotations: {}

## @param configMapLabels Define extra labels for the Linkwarden ConfigMap
##
configMapLabels: {}

## @section Linkwarden Secret parameters
##

## @param secretAnnotations Define extra annoations for the created Kubernetes secrets
##
secretAnnotations: {}

## @param secretLabels Define extra Labels for the created Kubernetes secrets
secretLabels: {}

## @section RBAC parameters
##

## Linkwarden RBAC settings
rbac:
  create: false
  enablePSP: false
  rules: []

## @section Linkwarden Service Account parameters
##

## FMJ Studios Linkwarden Service Account settings
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
## @param serviceAccount.create [default: true] Whether or not a service account should be created
## @param serviceAccount.annotations [object] Annotations to add to the service account
## @param serviceAccount.name [string] A custom name for the service account, otherwise linkwarden.fullname is used
##
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # The list of secrets mountable by this service account.
  # See https://kubernetes.io/docs/reference/labels-annotations-taints/#enforce-mountable-secrets
  secrets: []

## @section Linkwarden Probes
##

## Linkwarden Liveness Probe
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
##
livenessProbe:
  enabled: false
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10

## Linkwarden Readiness Probe
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
##
readinessProbe:
  enabled: false
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

## Linkwarden Startup Probe
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
##
startupProbe:
  enabled: false
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10
