# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

annotations:
  artifacthub.io/category: streaming-messaging
  artifacthub.io/license: MIT
  artifacthub.io/maintainers: |
    - name: FMJdev
      email: info@fmj.dev
  artifacthub.io/signKey: |
    fingerprint: 654213659810F05D16A7EDECB6C4D653E669D643
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/654213659810F05D16A7EDECB6C4D653E669D643
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: gotenberg
      image: docker.io/gotenberg/gotenberg:8.7.0
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Gotenberg Homepage
      url: https://gotenberg.dev/
    - name: Gotenberg Documentation
      url: https://gotenberg.dev/docs/getting-started/introduction
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
apiVersion: v2
appVersion: 8.7.0
kubeVersion: ">=1.26"
name: gotenberg
version: 0.1.1
description: Gotenberg is a Docker-powered stateless API for PDF files.
home: https://gotenberg.dev/
icon: https://user-images.githubusercontent.com/8983173/130322857-185831e2-f041-46eb-a17f-0a69d066c4e5.png
keywords:
  - documents
  - conversion
  - pdf
  - office
  - html
  - markdown
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: FMJdev
    email: info@fmj.dev
