# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: MIT
  artifacthub.io/maintainers: |
    - name: FMJdev
      email: info@fmj.dev
  artifacthub.io/signKey: |
    fingerprint: 654213659810F05D16A7EDECB6C4D653E669D643
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/654213659810F05D16A7EDECB6C4D653E669D643
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: uptime-kuma
      image: docker.io/louislam/uptime-kuma:1.23.13
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Uptime-Kuma Homepage
      url: https://uptime.kuma.pet/
    - name: Uptime-Kuma Documentation
      url: https://github.com/louislam/uptime-kuma/wiki
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
apiVersion: v2
appVersion: 1.23.13
kubeVersion: ">=1.26"
name: uptime-kuma
version: 0.1.1
description: Uptime-Kuma is an open-source, self-hosted fancy uptime monitoring tool
home: https://uptime.kuma.pet/
icon: https://raw.githubusercontent.com/louislam/uptime-kuma/953058c6a5047c82a58606e442c6e572e215e3ff/public/icon-512x512.png
keywords:
  - uptime
  - monitoring
  - website
  - database
  - tls
  - uptime-robot
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: FMJdev
    email: info@fmj.dev
