apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless.fullname" . }}
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels -}}
    {{- end }}
  {{- if .Values.service.annotations -}}
  annotations:
  {{- toYaml .Values.service.annotations }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.paperless.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "paperless.selectorLabels" . | nindent 4 }}
