# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

annotations:
  artifacthub.io/category: storage
  artifacthub.io/license: MIT
  artifacthub.io/maintainers: |
    - name: FMJdev
      email: info@fmj.dev
  artifacthub.io/prerelease: "false"
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Linkwarden Homepage
      url: https://linkwarden.app/
    - name: Linkwarden Documentation
      url: https://docs.linkwarden.app/
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
apiVersion: v2
appVersion: 2.4.8
kubeVersion: ">=1.26"
name: linkwarden
version: 0.0.1
dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
    version: ~13.2
description: Linkwarden is an open-source collaborative bookmark manager to collect, organize and preserve webpages
home: https://linkwarden.app/
icon: https://linkwarden.app/linkwarden.png
keywords:
  - bookmarks
  - archival
  - collaboration
  - linkding
  - linkace
  - archivebox
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: FMJdev
    email: info@fmj.dev
