# TODO(FMJdev): Swap these headers and footers with the actual service logos
vaultwarden:
  header: |
    <img src="https://seeklogo.com/images/H/helm-logo-9208DB3EE5-seeklogo.com.png" alt="Helm Logo" align="right" height="300" width="260"/>

    # Vaultwarden Helm Chart - CHANGELOG

  footer: |
    ---

    * **Chart**: `Vaultwarden`
    * **License**: MIT
    * **Author**: FMJ Studios

    <div align="center">

      **[fmj.studio](https://fmj.studio)**

    </div>

uptime-kuma:
  header: |
    <img src="https://seeklogo.com/images/H/helm-logo-9208DB3EE5-seeklogo.com.png" alt="Helm Logo" align="right" height="300" width="260"/>

    # Uptime-Kuma Helm Chart - CHANGELOG

  footer: |
    ---

    * **Chart**: `Uptime-Kuma`
    * **License**: MIT
    * **Author**: FMJ Studios

    <div align="center">

      **[fmj.studio](https://fmj.studio)**

    </div>

linkwarden:
  header: |
    <img src="https://seeklogo.com/images/H/helm-logo-9208DB3EE5-seeklogo.com.png" alt="Helm Logo" align="right" height="300" width="260"/>

    # Linkwarden Helm Chart - CHANGELOG

  footer: |
    ---

    * **Chart**: `Linkwarden`
    * **License**: MIT
    * **Author**: FMJ Studios

    <div align="center">

      **[fmj.studio](https://fmj.studio)**

    </div>

gotenberg:
  header: |+
    <img src="https://seeklogo.com/images/H/helm-logo-9208DB3EE5-seeklogo.com.png" alt="Helm Logo" align="right" height="300" width="260"/>

    # Gotenberg Helm Chart - CHANGELOG


  footer: |+
    ---

    * **Chart**: `Gotenberg`
    * **License**: MIT
    * **Author**: FMJ Studios

    <div align="center">

      **[fmj.studio](https://fmj.studio)**

    </div>

paperless-ngx:
  header: |
    <img src="https://seeklogo.com/images/H/helm-logo-9208DB3EE5-seeklogo.com.png" alt="Helm Logo" align="right" height="300" width="260"/>

    # Paperless-NGX Helm Chart - CHANGELOG

  footer: |
    ---

    * **Chart**: `Paperless-NGX`
    * **License**: MIT
    * **Author**: FMJ Studios

    <div align="center">

      **[fmj.studio](https://fmj.studio)**

    </div>
