---
{{- /*
  SMTP Secret
*/}}
{{- if not .Values.ntfy.smtp.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ntfy.secrets.smtp" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: ntfy
    {{- include "ntfy.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  username: {{ .Values.ntfy.smtp.senderUser | b64enc | quote }}
  password: {{ .Values.ntfy.smtp.senderPass | b64enc | quote }}
{{- end }}
---
{{- /*
  Web Secret
*/}}
{{- if not .Values.ntfy.web.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ntfy.secrets.web" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: ntfy
    {{- include "ntfy.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  publicKey: {{ .Values.ntfy.web.publicKey | b64enc | quote }}
  privateKey: {{ .Values.ntfy.web.privateKey | b64enc | quote }}
{{- end }}
---
{{- /*
  Twilio Secret
*/}}
{{- if not .Values.ntfy.twilio.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ntfy.secrets.twilio" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: ntfy
    {{- include "ntfy.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  accountSID: {{ .Values.ntfy.twilio.accountSID | b64enc | quote }}
  token: {{ .Values.ntfy.twilio.token | b64enc | quote }}
{{- end }}
---
{{- /*
  Upstream Secret
*/}}
{{- if not .Values.ntfy.upstream.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ntfy.secrets.upstream" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: ntfy
    {{- include "ntfy.labels" . | nindent 4 }}
    {{- if .Values.secret.labels }}
    {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 -}}
  {{- end }}
type: Opaque
data:
  token: {{ .Values.ntfy.upstream.accessToken | b64enc | quote }}
{{- end }}
