apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cachet.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: cachet
    {{- include "cachet.labels" . | nindent 4 }}
    {{- if .Values.configMap.labels }}
    {{- toYaml .Values.configMap.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.configMap.annotations }}
  annotations:
  {{- toYaml .Values.configMap.annotations | nindent 4 }}
  {{- end }}
data:
  APP_URL: {{ .Values.cachet.url | quote }}
  APP_ENV: {{ .Values.cachet.env | quote }}
  APP_DEBUG: {{ .Values.cachet.debug | quote }}
  CACHET_EMOJI: {{ .Values.cachet.emoji | quote }}
  CACHET_BEACON: {{ .Values.cachet.beacon | quote }}
  {{- /*
    Database settings
  */}}
  DB_DRIVER: {{ .Values.cachet.database.driver | quote }}
  {{- if .Values.cachet.database.host }}
  DB_HOST: {{ .Values.cachet.database.host | quote }}
  {{- end }}
  {{- if .Values.cachet.database.port }}
  DB_PORT: {{ .Values.cachet.database.port | quote }}
  {{- end }}
  {{- if .Values.cachet.database.name }}
  DB_DATABASE: {{ .Values.cachet.database.name | quote }}
  {{- end }}
  {{- if .Values.cachet.database.user }}
  DB_USERNAME: {{ .Values.cachet.database.user | quote }}
  {{- end }}
  {{- /*
    Driver settings
  */}}
  {{- if .Values.cachet.drivers.cache }}
  CACHE_DRIVER: {{ .Values.cachet.drivers.cache | quote }}
  {{- end }}
  {{- if .Values.cachet.drivers.session }}
  SESSION_DRIVER: {{ .Values.cachet.drivers.session | quote }}
  {{- end }}
  {{- if .Values.cachet.drivers.queue }}
  QUEUE_DRIVER: {{ .Values.cachet.drivers.queue | quote }}
  {{- end }}
  {{- if .Values.cachet.drivers.mail }}
  MAIL_DRIVER: {{ .Values.cachet.drivers.mail | quote }}
  {{- end }}
  {{- /*
    Mail settings
  */}}
  {{- if .Values.cachet.mail.host }}
  MAIL_HOST: {{ .Values.cachet.mail.host | quote }}
  {{- end }}
  {{- if .Values.cachet.mail.port }}
  MAIL_PORT: {{ .Values.cachet.mail.port | quote }}
  {{- end }}
  {{- if .Values.cachet.mail.user }}
  MAIL_USERNAME: {{ .Values.cachet.mail.user | quote }}
  {{- end }}
  {{- if .Values.cachet.mail.address }}
  MAIL_ADDRESS: {{ .Values.cachet.mail.address | quote }}
  {{- end }}
  {{- if .Values.cachet.mail.name }}
  MAIL_NAME: {{ .Values.cachet.mail.name | quote }}
  {{- end }}
  {{- if .Values.cachet.mail.encryption }}
  MAIL_ENCRYPTION: {{ .Values.cachet.mail.encryption | quote }}
  {{- end }}
  {{- /*
    Redis settings
  */}}
  {{- if .Values.cachet.redis.host }}
  REDIS_HOST: {{ .Values.cachet.redis.host | quote }}
  {{- end }}
  {{- if .Values.cachet.redis.database }}
  REDIS_DATABASE: {{ .Values.cachet.redis.database | quote }}
  {{- end }}
  {{- if .Values.cachet.redis.port }}
  REDIS_PORT: {{ .Values.cachet.redis.port | quote }}
  {{- end }}
