linkwarden:
  domain: "linkwarden.helm.private"
  nextAuthSecret:
    value: "PretendThisIsARandomString"
  ignoreUnauthorizedCA: true
  data:
    storageType: filesystem
    filesystem:
      rootPath: /data
      pvc:
        size: 5Gi
        storageClass: standard
        reclaimPolicy: Retain

  database:
    user: "linkwarden"
    password: "linkwarden"
    host: ""
    port: 5432
    name: "linkwarden"
    uri: ""

  auth:
    disableRegistration: false
    enableCredentials: true
    disableNewSSOUsers: false
    sso: []

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: mkcert-development-issuer
  # hosts:
  #   - host: "linkwarden.helm.private"
  #     paths:
  #       - path: /
  #         pathType: Prefix
  tls:
    - secretName: linkwarden-ingress-tls
      hosts:
        - "linkwarden.helm.private"

rbac:
  create: false
  rules: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
  secrets: []

livenessProbe:
  enabled: false
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10

readinessProbe:
  enabled: false
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

startupProbe:
  enabled: false
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 10

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: "postgres"
    username: "linkwarden"
    password: "linkwarden"
    database: "linkwarden"
    usePasswordFiles: false
  primary:
    name: primary
    persistence:
      enabled: true
      existingClaim: ""
      storageClass: standard
      accessModes:
        - ReadWriteOnce
      size: 5Gi
