linkwarden:
  domain: "linkwarden.helm.private"
  nextAuthSecret:
    value: "PretendThisIsARandomString"
  ignoreUnauthorizedCA: true
  data:
    filesystem:
      pvc:
        existingClaim: linkwarden-pvc

  database:
    user: "linkwarden"
    password: "linkwarden"
    host: ""
    port: 5432
    name: "linkwarden"
    uri: ""

  auth:
    disableRegistration: false
    enableCredentials: true
    disableNewSSOUsers: false
    sso: []

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: mkcert-development-issuer
  # hosts:
  #   - host: "linkwarden.helm.private"
  #     paths:
  #       - path: /
  #         pathType: Prefix
  tls:
    - secretName: linkwarden-ingress-tls
      hosts:
        - "linkwarden.helm.private"

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

startupProbe:
  enabled: true

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: "postgres"
    username: "linkwarden"
    password: "linkwarden"
    database: "linkwarden"
    usePasswordFiles: false
  primary:
    name: primary
    persistence:
      enabled: true
      existingClaim: ""
      storageClass: standard
      accessModes:
        - ReadWriteOnce
      size: 5Gi
