# Copyright FMJ Studios
# SPDX-License-Identifier: MIT

annotations:
  artifacthub.io/category: storage
  artifacthub.io/license: MIT
  artifacthub.io/maintainers: |
    - name: FMJdev
      email: info@fmj.dev
  artifacthub.io/prerelease: "false"
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/fmjstudios/helm
    - name: Linkstack GitHub Repository
      url: https://github.com/LinkStackOrg/LinkStack
    - name: Linkstack Documentation
      url: https://docs.linkstack.org/
  org.opencontainers.image.vendor: "FMJ Studios"
  org.opencontainers.image.licenses: "MIT"
apiVersion: v2
appVersion: 4.8.0
kubeVersion: ">=1.26"
name: linkstack
version: 0.0.1
description: LinkStack is a highly customizable link sharing platform with an intuitive, easy to use user interface
home: https://github.com/LinkStackOrg/LinkStack
icon: https://github.com/LinkStackOrg/branding/blob/c22886d7585246836d5e4e597484b92b51c76f0c/logo/svg/logo_color_bg_1.svg
keywords:
  - personal-website
  - profile
  - social
  - social-accounts
  - littlelink
  - linktree
  - linkstack
sources:
  - "https://github.com/fmjstudios/helm"
maintainers:
  - name: FMJdev
    email: info@fmj.dev
