ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: mkcert-development-issuer
  hosts:
    - host: gotenberg.helm.private
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: gotenberg-ingress-tls
      hosts:
        - gotenberg.helm.private

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

startupProbe:
  enabled: true

autoscaling:
  enabled: true
