{{- /*
  Next Auth secret
*/}}
{{- if not .Values.linkwarden.nextAuthSecret.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkwarden.secrets.nextAuth" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.secretLabels }}
      {{ toYaml .Values.secretLabels | nindent 4 -}}
    {{- end }}
    app.kubernetes.io/component: linkwarden
    {{- include "linkwarden.labels" $ | nindent 4 }}
  annotations:
    {{- if .Values.secretAnnotations }}
      {{ toYaml .Values.secretAnnotations | nindent 4 -}}
    {{- end }}
type: Opaque
data:
  token: {{ .Values.linkwarden.nextAuthSecret.value | b64enc | quote }}
{{- end }}
---
{{- /*
  Database Credential secret
*/}}
{{- if not .Values.linkwarden.database.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linkwarden.secrets.db" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.secretLabels }}
      {{ toYaml .Values.secretLabels | nindent 4 -}}
    {{- end }}
    app.kubernetes.io/component: linkwarden
    {{- include "linkwarden.labels" $ | nindent 4 }}
  annotations:
    {{- if .Values.secretAnnotations }}
      {{ toYaml .Values.secretAnnotations | nindent 4 -}}
    {{- end }}    
type: Opaque
data:
  uri: {{ include "linkwarden.db.uri" . | b64enc | quote }}
{{- end }}
---
{{- /* 
  Authentication secrets
*/}}
{{- range $_, $v := .Values.linkwarden.auth.sso }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "linkwarden.auth.secrets.base" $) $v.provider }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- if $.Values.secretLabels }}
      {{ toYaml $.Values.secretLabels | nindent 4 -}}
    {{- end }}
    app.kubernetes.io/component: linkwarden
    {{- include "linkwarden.labels" $ | nindent 4 }}
  annotations:
    {{- if $.Values.secretAnnotations }}
      {{ toYaml $.Values.secretAnnotations | nindent 4 -}}
    {{- end }}    
type: Opaque
data:
  clientId: {{ $v.clientId | b64enc | quote }}
  clientSecret: {{ $v.clientSecret | b64enc | quote }}
{{- if and (eq $v.provider "bungie") (not $v.existingSecret) }}
  apiKey: {{ $v.apiKey | b64enc | quote }}
{{- else if and (eq $v.provider "fusionauth") (not $v.existingSecret) }}
  tenantId: {{ $v.tenantId | b64enc | quote }}
{{- end }}
---
{{- end }}
