name: 'Testing'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - charts/**
  pull_request:
    branches:
      - main
    paths:
      - charts/**

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.15.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up Chart-Testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: ct-list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.ct-list-changed.outputs.changed == 'true'
        run: |
          ct lint --config config/ct-config.yaml

  lint-artifacthub:
    name: Lint Helm Charts with ArtifactHub Linter
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    container:
      image: public.ecr.aws/artifacthub/ah:v1.14.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ah lint
        working-directory: charts
        run: ah lint

  test:
    name: Test Helm Charts
    needs: ['lint', 'lint-artifacthub']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.15.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up Chart-Testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run kind to create a Kubernetes cluster
        if: steps.ct-list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1
        with:
          config: config/k8s/cluster/kind-config.yaml

      - name: Run chart-testing (install)
        if: steps.ct-list-changed.outputs.changed == 'true'
        run: |
          ct install --config config/ct-config.yaml